[package]
name = "kn"
description = "cd alternative - navigate by matching slices of path"
version = "0.1.0"
authors = ["micouy <m.powierza@tutanota.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "_kn"
path = "src/main.rs"

[dependencies]
regex = "1.4"
clap = "2.33"
thiserror = "1.0"
pretty_env_logger = "*"
log = "*"
tera = { version = "1", default-features = false }
