[package]
name = "se"
description = "cd by matching parts of path"
version = "0.1.0"
authors = ["micouy <m.powierza@tutanota.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4"
